q#+title:积水成渊-逐步定制自己的Emacs神器
#+author:天山飘雪

* Emacs入门
** 前言
本文介绍了Emacs编辑器的入门知识，看完本文读者会知道Emacs的基本用法以及如何通过Emacs来学习Emacs，这会让你觉得整个学习Emacs的过程都是在被“授之以渔”。

作者使用的Emacs版本是24.。3
原文链接：https://blog.csdn.net/elloop/article/details/50747251

** 下载和安装
Emacs的安装很简单，去[[https://www.gnu.org/software/emacs/][官网]]的[[https://www.gnu.org/software/emacs/#Obtaining][obtaining]]部分就能看到下载的镜像地址。

** 如何学习Emacs
*** 入门必看：Emacs Tutorial
进入Emacs Tutorial的方法：C-h t，即Ctrl+h，然后按t。

Tutorial里面你会掌握基本的键盘操作和Emacs里面的一些基本概念。这一步是初学者必看的基础知识，要继续往下学习之前请务必看完Tutorial并进行一些必要的练习。

*** Emacs Info 和 Emacs Manual
在掌握了Tutorial里的基础知识后，Emacs的Info Mode会成为你主要的学习场所。

Emacs Info是一个菜单列表，下面我叫它Info Mode，它列出了Emacs的一些关键部分，鼠标单击菜单项即可进入帮助文档页面。Info Mode定义了很多快捷键用来在Info系统里导航，使用C-h m来查看这些快捷键(C-h m命令的作用是：查看当前Mode的帮助信息)。

比如，m在Info Mode里是选择菜单的意思，按下m，在下方的小窗口中(minibuffer)，Emacs会问你：你要选哪个菜单项？，然后等待你的输入，你输入：Emacs RET, 这样就进入了Emacs Manual。RET就是回车键的意思。

Emacs Manual就是Emacs编辑器的帮助手册。里面有对Emacs个方面的详细介绍，要掌握Emacs对这个手册的学习和参考当然是很重要也是很方便的。Emacs Manual仍然是在Info Mode下，因此你可以继续使用Info Mode下的快捷键来浏览。这就是所谓的“在Emacs中学习Emacs”。

*** Self Documentation
对于工作中的我们来说，学习东西通常是边用边学，不大可能有人整天在Emacs Manual里学习。在使用过程中会产生很多疑问，比如忘记了某个命令的含义、忘记了某个Mode下的快捷键、想知道某个变量的含义等等，这个时候你不需要Google，只要问Emacs就好了。

怎么问Emacs呢？

Emacs是一个“自文档化”的软件(Self-Documenting)，任何你能看到的东西，比如：命令、按键序列、菜单项，或者是某个出现在文档里的术语，这些东西都可以在Emacs内部找到答案，你只需使用C-h前缀开头的几个命令就能知道任何问题的答案。它们的使用方法如下：

    - C-h k 会告诉你任何命令的帮助信息
    - 使用C-h k来询问Emacs其他帮助命令的作用，比如：C-h f, C-h v, C-h w, C-h m, C-h b, C-h a, C-h k等等。比如我要知道C-h k自己是用来干嘛的，我可以：C-h k C-h k
    - 使用C-h系列的命令来获取任何帮助
    - C-h C-h用来查看“帮助的帮助

*** EmacsWiki
[[https://www.emacswiki.org/][专门提供Emacs帮助文档和Emacs Lisp学习文档的网站]]

在这里能学到Emacs Manual中没有的东西，有很多前人总结的经验。对于入门的用户，这篇文章是很有帮助的：[[https://www.emacswiki.org/emacs/SelfDocumentation][Self Documentation]]

*** 入门视频教程
Youtube上有很多Emacs的入门视频教程，你需要科学上网才能看到。这里先推荐一个做的比较好的入门视频：

[[https://www.youtube.com/watch?v=MRYzPWnk2mE][Emacs入门视频]]

** 彩蛋：在Emacs中玩游戏
C-h i 进入Info Mode, 输入mEmacs进入Emacs Manual，输入mAmusement, 进入游戏帮助界面，可以查看所有可玩的游戏。
这些游戏的进入方式是：M-x + <game-name>, 比如，我要玩俄罗斯方块(tetris), 我就输入：M-x tetris.

不知道怎么玩？ 问Emacs，还记得怎么获得当前Mode下的帮助吗？ 对，C-h m即可。下图是Emacs中俄罗斯方块的画面和右侧的帮助信息。

** 下集预告
想知道在上图中我是如何把Emacs主题变成Solarized主题的吗？并且是如何去掉了菜单栏、工具栏和滚动条，有更大的空间来展示文本信息。

下一篇文章将讲解如何定制Emacs的外观，让它变成你喜欢的样子，并且讲解如何比较方便的让你的Emacs配置做到“一次配置，随处可用”。

_______________________________________________________________________________


* 基本的定制
** 前言
本文介绍了如何定制Emacs的外观和如何组织Emacs配置文件以做到“一处配置随处可用”。外观定制部分仅举个例子，包括：菜单栏、工具栏、滚动条、字体设置、主题，重在讲解定制方法，读者一旦掌握定制的方法，就可以做更多的定制。

定制Emacs有两种方式：

    - 通过Emacs的Customize系统，类似传统软件的GUI操作
    - 通过修改Emacs配置文件(.emacs或者init.el，后面介绍这个配置文件)

第一种方式其实也是在修改Emacs配置文件，只不过是Emacs自动修改的。对于初学者或者是不喜欢去手动操作配置文件的用户，使用Customize系统是更好的选择

** 去掉菜单栏、工具栏、滚动条
所有的定制操作有一个统一的入口：M-x customize RET。进入Customize Mode之后的界面如下：

customize.jpg

定制的操作很简单，选择要设置的项目编辑、保存即可。关键在于如何找到要设置的项目，可以使用页面上方的搜索框来搜索要设置的选项。使用C-h m来获得使用Customize Mode的帮助信息。
以隐藏菜单栏来举例，我在search里输入”menu bar”回车，在搜索结果里将光标移动到”Menu Bar Mode”那一行行首，按TAB键，光标会自动定位到Toggle按钮上，按回车键来切换设置状态，设置为“off”之后，再一下TAB将光标移动到下面的State按钮上，按下回车，Emacs提示你保存状态，选择“1”，为以后的sessio都使用这个设置。 如下图所示：
hide-menu-bar

#+BEGIN_QUOTE
小提示：在Customize Mode下，TAB键自动将光标移动到下一个按钮，S-TAB移动到上一个按钮。
#+END_QUOTE

对于隐藏工具栏和滚动条是一样的操作，把搜索词替换为“tool bar”和“scroll bar”即可。要关闭的两个Mode分别是：
   - Tool Bar Mode
   - Scroll Bar Mode。

** 更换字体
字体的设置可以按如下操作进行：

   -  M-x customize-group RET basic-faces RET，进入了Customize Group的Basic Faces设置分组，将光标移动到Default那一行，按回车键，展开Default分组：

basic_faces.jpg

   - 可以看到Font Family那项就是字体的名称，光标移动到那行的行首，按TAB键会自动定位到名称编辑框里进行修改，可以根据需要修改其它的设置。修改之后，点击State按钮，类似之前修改菜单栏的操作一样，要对修改进行保存，要为以后的session都使用这个字体那就根据提示输入“1”即可。

** 更改主题
在介绍如何安装Package之前，这篇文章只讲如何在Emacs自带的主题直接进行切换。

如果只是临时想修改主题，那么可以这么操作：输入M-x customize-themes RET, 会看到Emacs自带的十几种主题，光标移动到某个主题，然后按回车键，当前的session就会切换到对应主题。如果想在Emacs重启后仍然保留需要点击上面的保存按钮。

customize_themes.gif

** 自定义操作小结
前面介绍的定制操作提到了三种进入设置页面的方法，第一种是通过M-x customize RET，进入设置的主页面，然后使用搜索功能，定位到具体的设置选项。

第二种是使用M-x customize-group然后进入Basic Faces分组。

第三种是直接进入主题设置页面：M-x customize-themes。

通常某个具体的设置项都对应着Emacs的一个变量，在熟悉了设置项之后，则可以直接定位到具体的设置页面，比如假设我知道了控制菜单栏显示的变量叫：menu-bar-mode，那么我可以使用:

M-x customize-variable RET menu-bar-mode RET 直接进入菜单栏设置界面。

综上所述，我们目前掌握的进行定制操作的命令分为以下四类：

   - M-x customize : 进入设置主页，通过搜索来导航
   - M-x customize-group ：按分组来设置，需要指定分组名，需要对设置分组有一定的了解
   - M-x customize-variable ：定位到具体的某个变量，需要对要设置的项的变量名熟悉
   - M-x customize-themes ：以设置主题为代表的这类命令，对Emacs某个方面进行设置的命令，需要对设置系统比较熟悉。

** 让你的Emacs个性化设置随处可用
当你的Emacs配置复杂到一定程度以后，让你在另一台设备上重新设置一遍是很费精力的。就像你希望你的浏览器书签可以在任何设备上可用一样，你也希望你最喜欢的Emacs个性化设置也一样随处可用，这不是什么难事，有很多办法。

在介绍如何做到这一点之前，首先要确定的是，我们的Emacs配置文件在哪里？

默认情况下，你的Emacs配置文件是在($HOME)/.emacs这个文件里的。如果找不到这个目录和文件，请参考下面那节“我的配置文件在哪里”。

安装的扩展Package等文件是放在($HOME)/.emacs.d/这个目录下的。你也可以把.emacs文件重命名为init.el, 然后把它也放在.emacs.d这个文件夹下，这样就维护一个目录就行了。

因此，($HOME)/.emacs.d/这个文件夹就是你的私人Emacs定制内容，让它随处可用即可。用U盘、云盘啥都行，很多人都把.emacs.d建成一个独立仓库托管在github上，在实现了云端存储的同时，还方便版本管理，记录每次的修改，所以建议使用这个方案。
