cs#+title: 情绪管理心得

* 对于情绪管理的认识
对于情绪的认识，最早来源于美国哈佛大学心理学教授丹尼尔·戈尔曼，他认为情绪是指情感及其独特的思想、心理和生理状态，以及一系列行动的倾向。 后来，去查阅了一下相关资料，发现对于情绪，有着很多种的定义，比如拉扎勒斯认为”情绪是来自正在进行着的环境中好的或不好的信息的生理心理反应的组织，它依赖于短时的或持续的评价。“ 而阿诺德在1960年指出”情绪是对趋向知觉为有益的、离开知觉为有害的东西的一种体验倾向。这种体验倾向为一种相应的接近或退避的生理变化模式所伴随。”类似这样的对于情绪的定义，有不下20种。

何源老师在《教师情绪管理》一课中指出“情绪是人对客观事务的态度体验，是人的需要是否获得满足的反映。”同时，河源老师引用Robert Plutchik的观点，列举了八种基本情绪：恐惧、悲伤/抑郁、厌恶、愤怒、惊讶。期待，快乐、信任。 这就把抽象的情绪用非常具体的形式给表现了出来，让我一下就理解了情绪到底为何物。 接着，何源老师通过构成情绪的三大部分：想法、感受、行为， 详细的描绘了情绪的前因后果，我也因此更加深刻的理解了情绪的产生，发展和产生最终的的行为的原因。 这部分内容对于我在课堂上把控学生的情绪，调动学生的课堂气氛，缓解课堂的紧张感有着及其重要的作用。

曾经，我有过这样的一堂课，当我走进教室的时候，发现几乎所有的学生都达拉着脑袋，毫无生气， 几个女生眼睛红红的，貌似哭过， 大部分男生则是一改以往的热闹，两眼无神的在发呆，这明显是一种不好的情绪。 我没有立马开始上课，而是安安静静的看着他们，同时开始注意他们手边的东西。 我发现部分同学盯着桌上的一张试卷，一脸的绝望，一脸的生无可恋的样子。 我在教室慢慢的绕了一圈，终于发现了原因，原来是刚刚进行了数学考试，题目很难，成绩普遍不理想，数学老师惨绝人寰的要求每位同学回家让家长签字。班里几乎所有的同学都在思索着一个相同的问题：这个分数，怎么回去交代？ 通过何源老师在《教师情绪管理》这课中情绪三部分的阐述，我们可以做出这样的分析：由于数学考试太难，成绩不理想，回家又要家长签字，于是 同学们普遍产生了一种回去如何交代的想法，这个想法使得他们感受到了前所未有的焦虑和恐惧，于是，便有了现在的一种及其压抑的表现。 得知病因之后，我立马和数学老师沟通，商量对策，并请数学老师进入教室，讲述这次考试的难度，解释这次成绩低的原因，并请数学老师根据同学们的对于学好数学的愿望做出了表扬。 同时宣布，不请家长签字，但是要每题认真订正，全部搞懂，再次基础上，下次再考一次，看大家表现。 瞬间，全班的同学的眼神活了。 并且，此后，班里的数学成绩越来越好，我这门和数学不相关的课程也越来越受同学们的欢迎。

现在听了何源老师的课，回过头再去看这件事，真的是要感谢情绪。情绪是把双刃剑， 用的不好会焦虑、恐惧，用的好就是化压力为动力，更上一层楼。
