#+title:Web开发基础教程
#+author:chen
#+date:[2020-06-25 四]
* 第一部分 Html基础知识
** 第一讲：了解Html，web和internet
   Internet 是为在计算机之间交换信息而构成的国际网络，万维网(www)是巨大的信息，艺术，商业互联库。
   
   Html(Hypertext Markup language，超文本标记语言)是一种用户制作网页的计算机语言。
*** 互联网的起源

    Internet 起源于 60 年代中期美国国防部下属的 DARPA(Defense Advanced ResearchProject )的网络计划，科学家和科研人员开发 internet 以便于不同的研究机构间通信和共享信息。为了实现这一点，他们创建了新的协议以使计算机之间能够交流信息.现在的 internet 就是建立的这些协议的基础上的。

    随着互联网的研究机构，大学，和高新技术公司的逐渐增多，Internet 协议变得越来越流行， 这些协议允许你发送 Email，利用 FTP 交换文件，利用 bbs 阅读帖子等等。

    Email:电子邮件通过 smtp(简单邮件传输协议)从一个用户发送给另外一个用户.Email 可以说是互联网上最流行的应用。

    FTP(文件传输协议):网络上交换文件的一种方法，可以把文件放在 FTP 文件服务器上，你可以利用客户端程序获取这些文件。
    
    TCP/IP(传输控制协议/网间协议)在网络和计算机之间传输信息。

*** 什么是www
    1990 年一种新的被称为 Http(超文本传输协议)出现，www(World Wide Web)也随之诞生，WorldWide Web 也简称 W3 或 www 或 Web，是基于 Http 协议的巨大网络。

*** web浏览器介绍

*** 超链接
 位于不同服务器上的文件可以通过超链接组织起来，在同一个文件中也可以通过超链接在文件的不同部分之间进行跳转.超链接可以指向文本，图像，音频，视频等媒体文件，在网页上文本的超链接是高亮显示的，并且有下划线，用户可以点击，链接的指定资源. 有了超链接，Web 就成为一个难以想象的信息网络，有了超链接你就可以链接到你感兴趣的资源。

*** Url介绍
    Url:统一资源定位器，简单的理解为网页或 internet 上的其它文件的地址，Web 上的每个Url 都是唯一的. 简单的 Url 构成: http://www.szonline.net/ 这是深圳热线的网站的 Url，它包括web 协议 (http)，后面跟”:”之后是斜杠”//”之后是网站的域名.域名是大小写不敏感的。

    带 ip 地址的 Url:http://201.122.122.3 这组数字给出了互联网上的某台机器的 Ip 地址，他和使用域名访问是等价的实，际上我们输入域名后，也是要经过域名服务器(DNS)解析成 Ip 地址后进行
访问的.使用域名是为了方便记忆。

**** 常用的三个协议
     | 协议关键字 | 描述           |
     | ftp://     | 文件传输协议   |
     | http://    | 超文本传输协议 |
     | file://    | 本地文件       |
 
     #+begin_quote
     rul中是不允许有空格的。
#+end_quote

*** Html 介绍
    Html:超文本标记语言 超文本是指定义了额外特征的普通文本，如格式，图像，多媒体，其它链接等。标记语言是一种特殊类型的计算机语言，因为他只关心对文件中的个部分按其功能分类，表明哪一部分是文章的标题，哪一部分是子标题等等。Html 是把用户的文件按各部分进行分类，以便浏览器可以正确的显示它。Html 标准是由 W3C 负责的，我们可以访问他们的网站:http://www.w3.org ，Html 是 SGML 标
准通用标记语言家族中的一员 ，Html 的第一版本是 Html1.0， 之后又经历了Html+，Html2.0，Html3.0，现在发展到了 Html4.0，日趋完善和强大。

** 第二讲 建立你的第一个Html页面
*** Html概述
    HTML 表示超文本标记语言(Hyper Text Markup Language)。

    HTML 文件是一个包含标记的文本文件。 这些标记保速浏览器怎样显示这个页面。 HTML 文件必须有 htm 或者 html 扩展名。 HTML 文件可以用一个简单的文本编辑器创建。
*** 建立我们的第一个Html页面
    #+begin_src html
    <html>
       <head>
            <title>江雪</title>
      </head>
         <body>
            <center><b>江雪</b></center><br>
            <center>千山鸟飞绝,</center><br>
            <center>万径人踪灭.</center><br>
            <center>孤舟蓑笠翁,</center><br>
            <center>独钓寒江雪.</center>
         </body>
    </html>

    #+end_src
** 第三讲 设计漂亮的Html文档
*** 标签的缩进
*** Html的空格规则
    在 Html 中的空格规则为:多个空格,制表符,回车将转换为单一的空格。
*** 在Html中使用字符实体
    - 一个字符实体拥有三个部分:
           - 一个 and 符号(&)
           - 一个实体名或者一个实体号
           - 最后是一个分号(;)
  - 常用字符实体
| 字符 | 实体名  |
| 空格 | &nbsp； |
| <    | &lt;    |
| >    | &gt;    |
| &    | &amp;   |
| “   | &quot;  |

*** 使用body属性定制丰富多彩的面页
    我们通过使用 body 标签的属性,定制文档的外观,包括页面文字和链接的前景色和背景色以及背景图案等等。
**** Html是如何表示颜色的
     
     - 用颜色名称表示：如:红色 red,绿色 green ,蓝色 blue,白色 white ,黑色 black,黄色 yellow,灰色 gray,银色 silver
     - 用RGB代码表示：用 16 进制表示的(0-F),RGB 码以#后跟 6 为 16 进制的字符表示,比如蓝色表示为 :#0000FF, 绿 色 为 #00FF00 等 等 

     在body 中 有 六 个 属 性 我 们 可 以 控制:bgcolor,background,text,link,vlink,alink
**** bgcolor控制页面背景颜色
#+begin_src html
<html>
<head><title>使用背景颜色</title></head>
<body bgcolor="#d0d0d0">
<h4>热爱生命</h4>
<p>
我不去想是否能够成功<br>
 既然选择了远方
<br>
便只顾风雨兼程
</p>
<p>
我不去想能否赢得爱情<br>
<br>
就勇敢地吐露真诚
</p>
 <p>
我不去想身后会不会袭来寒风冷雨<br>
 既然目标是地平线
<br>
留给世界的只能是背影
</p>
<p>
我不去想未来是平坦还是泥泞<br>
 只要热爱生命<br>
一切,都在意料之中
</p>
</body>
</html>
#+end_src
**** background使用背景图片
#+begin_src html
<html>
<head><title>使用背景颜色</title></head>
<body background="bufferfly.gif">
<h4>热爱生命</h4>
<p>
我不去想是否能够成功<br>
 既然选择了远方
<br>
便只顾风雨兼程
</p>
<p>
我不去想能否赢得爱情<br>
 既然钟情于玫瑰
<br>
就勇敢地吐露真诚
</p>
 <p>
我不去想身后会不会袭来寒风冷雨<br>
 既然目标是地平线
<br>
留给世界的只能是背影
</p>
<p>
我不去想未来是平坦还是泥泞<br>
 只要热爱生命
<br>
一切,都在意料之中
</p>
</body>
</html>
#+end_src
**** text 属性使用文字颜色
     在body中使用text属性改变文字的颜色
**** link 设置超文本链接的颜色（未访问的链接）vlink设置已访问过的链接的颜色
*** 使用Font标签定制字体<font> </font>
    font的属性：
    - color ：控制文字的颜色
    - size：控制文字的大小，共1-7，7个字号，7号最大（比H1还要大）。
      - size="-1" 表示比默认字号小1
      - size="+1" 表示比默认字号大1
  - face：设置字体，如：<font face=”Arial”>
