#+title:php开发实战权威指南
#+author:ShadowFish
#+data:<2019-08-20 Tue>
#+STARTUP: indent
#+html_head: <link rel="stylesheet" type="text/css" href="./css/worg.css"/>
#+data:2017-8
#+num:t
#+toc:4
* 《PHP开发实战权威指南》



* 第1章 PHP基础知识与XHTML
**  PHP的发展与特点
***  PHP的特点
1. 免费开源，自由获取
2. 移植性强，组件丰富
3. 语言简单，开发高效
4. 功能强大的函数库
5. 应用范围广泛
***  PHP 5.5.3 之后的新特性
1. 对滥用的语法进行规范
2. 推出MySQL驱动mysqli以提高效率
   1) 编译更加方便，不需要libmysql，已经内置在源码中 。
   2) 使用PHP许可，避免版权问题
   3) 使用PHP的内存管理，支持PHP的内存限制（memory_limit）。
   4) 所有数据在内存中只有一份，之前的libmysql有两份。
   5) 提供性能统计功能，并帮助分析瓶颈。
   6) 在驱动层增加缓层机制。
3. PHP 5.3 安全和性能的提升
4. 延迟静态绑定
5. 更过的新特性
   1) 名字空间，用来解决命名被污染
   2) 新的魔法函数_callStatic，即原来的_call静态模式
   3) 支持变量调用静态，可以通过$someClass::$method（）调用。
   4) 增加日期函数date_create_from_format
   5) 新增了类似JavaScript中的匿名函数和闭包
   6) 新增魔法常量_DIR_，用来解决路径问题
*** B/S结构
**** B/S模式的模型结构
B/S模式，即浏览器/服务器模式，是一种从传统的二层CS模式发展起来的新的网络结构模式，其本质是三层结构C/S模式
**** B/S模式的工作原理
客户端运行浏览器软件，浏览器以超文本形式向web服务器提出访问数据库的要求，web服务器接受客户端请求后，将这个请求转化为SQL语法，并提交给数据库服务器，服务器得到请求后，验证其合法性，并进行数据处理，然后将处理后的结果返回给web服务器。web服务器将得到的所有结果进行转化，变成html文档形式
