
#+title:精通PHP+MySQL应用开发
#+author:ShadowFish
#+data:<2019-08-20 Tue>
 
* 第一章 初识PHP
** 初识PHP
建PHP开发环境， 并实现第一个PHP程序。
*** 走近PHP
1. PHP的本质
PHP是一种HTML嵌入式语言， 运行于服务器端。

嵌入HTML是指：利用HTML标记， PHP代码可以和HTML混为一体， 并可由Web服务器（如IIS、Apache等）将其从HTML中识别出来， 交给PHP解释器执行， 以完成一定的功能， 最后将执行结果返回浏览器。

1. PHP的优势
   - 速度
   - 安全
   - 跨平台
   - 易用性
   - 功能性
*** 搭建开发环境
1. 软件准备
2. 安装PHP
3. 配置apache
4. 安装MySQl
5. 安装PHPMyAdmin
*** 用PHP实现 HelloWorld
#+BEGIN_SRC php
<?php
    echo "Hello World!<br>";
    phpinfo();
?>
#+END_SRC
** 第一个PHP程序 —— 我的书房
#+BEGIN_SRC php
<!doctype html>
<html>
    <head>
        <title>显示时间</title>
        <meta charset="utf-8" />
    </head>
    <body>
        <center>
            <h1 style="background:#cccccc " >
                ..欢迎光顾我的书房..
            </h1>
        </center>
        <?php
        $current_date = date(" dS of F, Y h:i:s A");
        echo "现在是：$current_date. <br>";
        ?>
        <br />
        <form action="say_bye.php" method="post" >
            <input type="submit" name="submit" value="永不再来" ></input>
            <input type="submit" name="submit" value="还会再来" ></input>
        </form>
    </body>
</html>

#+END_SRC
*** 我的书房之显示时间
data（）函数， 可以查阅PHP函数手册
*** 我的书房之临别赠言
- form的action属性
- $_POST[''] 传递表单变量
** 在HTML中嵌入PHP
*** 把PHP嵌入HTML(四种分界符）
- <?php   ?>   标准分界符
- <?      ?>   简写分界符
- <script lanuage="php">    </script>    JavaScript/VBScript风格分界符
- <%      %>   ASP分界符

#+BEGIN_QUOTE
第一中方法最常用，第二和第四种方法，需要在配置文件php.ihi中进行设置
short_open_tag = on;
asp_tags = on; 
#+END_QUOTE

#+BEGIN_QUOTE
&#60 代表 <
&#62 代表 >
#+END_QUOTE
*** PHP语句结束符
用；表示语句结束
*** 注释
- //         注释一行代码
- //*  *//     注释多行代码
- #          UNIX Shell语法的注释， 注释一行代码
*** 引用文件
- require（ ）—— 当解释PHP程序时，解释器会事先就读入require所指定的文件， 使其变为调用的PHP文件的一部分。  通常放在调用文件的前部。
- include （ ） —— 当解释器读到include时， 才会把指定的文件读进来。  一般放在流程控制处理中。
* 第二章 PHP程序设计基础
** 数据类型
*** 理解数据类型
- string  —— 字符串
- integer —— 整数
- double —— 浮点数
- array —— 数组
- object —— 对象
*** 字符串
- 字符串中的反斜杠"\"为转义字符。
- 双引号中的变量会进行计算。
- 转义字符
| 转义字符 | 描述        |
| \n       | 换行        |
| \t       | 制表符      |
| \r       | 回车符      |
| \$       | 美元        |
| \\       | 反斜杠字符  |
| \Onnn    | 八进制数nnn |
| \Xnnn    |十六进制         |

*** 变量
**** 理解变量
**** 声明变量
标识符前加上$, PHP的变量区分大小写， 定义变量时不需要指定变量类型， PHP的变量类型由变量的值的类型来确定。

两个常用的函数， 用于查看变量状态
- isset（string val_name): 查看变量是否已经生成， 其参数为变量名（带$号）， 变量生成则返回true， 否则返回false。
- empty（string val_name): 查看变量是否为空， 其参数为变量名（带$好）， 若变量为空或0则返回true， 否则返回false。
cyq@cyqdeMacBook-Pro note % ls
ls
C++????????????.org					mac?????????php????????????.org
EMACS????????????.odt					mysql????????????.org
EMACS????????????.org					org-mode.org
Emacs Lisp????????????.org				pic
HTML5??????.org						spacemacs??????.org
Html & CSS ?????????????????????.org			spacemacs????????????.org
Master Emacs in 21 Days.org				vi??????.org
PHP???MySQL Web??????.html				???c++????????????????????? ????????????.org
PHP???MySQL Web??????.org				???php???????????????????????????.org
Spacemacs Rocks Episode2.org				?????????emacs?????????.org
emacs????????????.org					?????????HTML5+CSS3+JavaScript???????????????.org
emacs??????????????????.org				????????????????????????.org
emacs??????????????????.org_archive			??????????????????Emacs????????????????????????.org
emacs????????????.org					?????????PHP????????????.org
emacs??????.org						????????????-?????????????????????Emacs??????.org
linux??????????????????.org				????????????-?????????????????????Emacs??????.org~
linux???????????????.org				??????PHP+MySQL????????????.org
linux???????????????.org				??????PHP+MySQL????????????.org~
cyq@cyqdeMacBook-Pro note % 
